name: "LLNL Software Portal"
author: "Ian Lee <lee1001@llnl.gov>"
title: LLNL Software Portal
description: "LLNL Software Portal"

url: "http://software.llnl.gov"

# paginate: 10

collections:
  software:
    output: true

# LLNL Piwik Analytics https://analytics.llnl.gov
piwik_id: 250

exclude:
  - _software/template.md
  - _software/chaos.md  # Hide chaos due to missing information

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: llnl/llnl.github.io
gems: ['jekyll-github-metadata']

defaults:
  -
    scope:
      path: ""
      type: "software"
    values:
      layout: "entry"
      permalink: "/software/:title/"

markdown: kramdown
permalink: pretty
highlighter: pygments
