name: "LLNL Software Portal"
author: "Ian Lee <lee1001@llnl.gov>"
title: LLNL Software Portal
description: "Lawrence Livermore National Laboratory Software Portal"

url: "http://software.llnl.gov"

# paginate: 10

# LLNL Piwik Analytics https://analytics.llnl.gov
piwik_id: 250

# Google Analytics ID
google_analytics:
  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: llnl_opensource

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: llnl/llnl.github.io
gems:
  - jekyll-github-metadata
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

markdown: kramdown
permalink: pretty
highlighter: pygments
