name: "LLNL Software Portal"
author: "Ian Lee <lee1001@llnl.gov>"
title: LLNL Software Portal
description: "LLNL Software Portal"

url: "http://llnl.github.io"

# paginate: 10

collections:
  software:
    output: true

markdown: rdiscount
permalink: pretty
highlighter: pygments
