name: "LLNL Software Portal"
author: "Ian Lee <lee1001@llnl.gov>"
description: "LLNL Software Portal"

url: "http://localhost:4000"

# paginate: 10

collections:
  software:
    output: true

markdown: rdiscount
permalink: pretty
highlighter: pygments
