name: "LLNL Software Portal"
author: "Ian Lee <lee1001@llnl.gov>"
title: LLNL Software Portal
description: "LLNL Software Portal"

url: "http://llnl.github.io"

# paginate: 10

collections:
  software:
    output: true

exclude:
  - _software/template.md
  - _software/chaos.md  # Hide chaos due to missing information

defaults:
  -
    scope:
      path: ""
      type: "software"
    values:
      layout: "entry"
      permalink: "/software/:title/"

markdown: rdiscount
permalink: pretty
highlighter: pygments
